/**
 * Fleshed-Out Character Buildings Catalog for All 76+ Characters.
 */

export const CHARACTER_BUILDINGS_CATALOG = [
  {
    ownerId: 'buffett',
    ownerName: 'Warren Biffle',
    buildingName: 'Berkshire Hathaway Financial Tower & Cherry Coke Diner',
    city: 'Kyoto',
    coordinates: { x: 10, y: 20 },
    constructionCost: 50000000,
    architecture: 'Suburban Neo-Classical Brick & Glass with Retro 1950s Diner Counter',
    dailyYield: 35000,
    specialPerk: 'Restores Energy & Grants +$35,000 Daily Compound Yield',
  },
  {
    ownerId: 'jobs',
    ownerName: 'Steve Jobs',
    buildingName: 'Apple Unibody Curved Glass Campus',
    city: 'Tokyo',
    coordinates: { x: 15, y: 25 },
    constructionCost: 150000000,
    architecture: 'Seamless 360-Degree Curved Unibody Solar Glass Ring Structure',
    dailyYield: 75000,
    specialPerk: '+15% Tech Stock Valuation Hype & High-Speed Product Launch',
  },
  {
    ownerId: 'musk',
    ownerName: 'Elan Rusk',
    buildingName: 'Giga Factory & SpaceX Starbase Launchpad',
    city: 'Tokyo',
    coordinates: { x: 20, y: 30 },
    constructionCost: 300000000,
    architecture: 'Ultra-Automated Solar Gigafactory Complex with Vertical Rocket Silos',
    dailyYield: 120000,
    specialPerk: 'Pumps Crypto Hype & Generates +$120,000 Daily Manufacturing Revenue',
  },
  {
    ownerId: 'rockefeller',
    ownerName: 'John D. Rockefeller',
    buildingName: 'Standard Oil Central Refinery & Pipeline Network',
    city: 'Sapporo',
    coordinates: { x: 25, y: 35 },
    constructionCost: 200000000,
    architecture: 'Heavy Industrial Steel Cracking Towers & Interconnected Crude Oil Pipelines',
    dailyYield: 90000,
    specialPerk: 'Monopoly Monopoly Dividend Squeeze: +$90,000 Daily Oil Revenue',
  },
  {
    ownerId: 'carnegie',
    ownerName: 'Andrew Carnegie',
    buildingName: 'Homestead Mega Steel Mill',
    city: 'Sapporo',
    coordinates: { x: 30, y: 40 },
    constructionCost: 120000000,
    architecture: 'Massive Brick Blast Furnaces & Heavy Railroad Loading Docks',
    dailyYield: 60000,
    specialPerk: 'Subsidizes Real Estate & Building Construction Costs by 20%',
  },
  {
    ownerId: 'ford',
    ownerName: 'Henry Ford',
    buildingName: 'River Rouge Automated Assembly Complex',
    city: 'Sapporo',
    coordinates: { x: 35, y: 45 },
    constructionCost: 100000000,
    architecture: 'Mile-Long Automated Moving Conveyor Belt Manufacturing Hub',
    dailyYield: 50000,
    specialPerk: '+15% Daily Company Dividend Yield Across All Factories',
  },
  {
    ownerId: 'capone',
    ownerName: 'Al Capone & Lucky Luciano',
    buildingName: 'Chicago Outfit Speakeasy Hotel & Casino',
    city: 'Osaka',
    coordinates: { x: 40, y: 50 },
    constructionCost: 40000000,
    architecture: 'Subterranean Art Deco Velvet Speakeasy beneath a Luxury Grand Hotel',
    dailyYield: 45000,
    specialPerk: 'Extracts +$45,000 Daily Syndicate Protection Tolls & Reduces Heat',
  },
  {
    ownerId: 'hoover',
    ownerName: 'J. Edgar Hoover',
    buildingName: 'FBI National Crime Information Center & Bureau HQ',
    city: 'Osaka',
    coordinates: { x: 45, y: 55 },
    constructionCost: 130000000,
    architecture: 'Fortified Brutalist Concrete Intelligence Citadel with Wiretap Arrays',
    dailyYield: 0,
    specialPerk: 'Executes Federal RICO Indictments & Increases Wiretap Speed by +25%',
  },
  {
    ownerId: 'powell',
    ownerName: 'Jerome Powers',
    buildingName: 'Federal Reserve Gold & Reserve Depository HQ',
    city: 'Tokyo',
    coordinates: { x: 50, y: 60 },
    constructionCost: 250000000,
    architecture: 'Granite Columned Neoclassical Central Bank Vault Complex',
    dailyYield: 0,
    specialPerk: 'Direct Benchmark Rate Adjustment Control & Inflation Liquidity Pumps',
  },
]
