"""
Board of Realities - NPC free-text interaction backend.

A tiny FastAPI service that lets the player type free text at an NPC and
get back a live, in-character reply generated by an LLM, instead of a
canned/keyword-matched response. For the Capital Syndicate roster (finance
titans, crime syndicate, presidents, Fed/FTC chairmen, agency heads - ~90
characters) the reply also carries a persuasion verdict: whether THIS
specific character, given their real personality/biography data, would
actually agree to what the player asked, plus how the exchange shifted
their opinion of the player.

Run with (from the project root):
    uvicorn backend.main:app --reload --port 8091

The frontend (Vite dev server on http://localhost:5173) calls this via
src/utils/npcChatClient.js -> POST http://localhost:8091/npc-interact

(Port 8091, not the more obvious 8000 - 8000 is already occupied on dev
machines that run other local FastAPI services alongside this repo. Also not
8079, this project's original port - abandoned after a dev-machine-specific
orphaned socket on 8079 wouldn't release even under a forceful process kill.)

The OpenAI API key is read from the project's root `.env` (OPENAI_API_KEY)
and never leaves this process - the browser never sees it.

Model/endpoint note: this project's OpenAI key only has access to
`gpt-5.6-luna` via the /v1/responses endpoint (verified directly against
the API - gpt-4o-mini and every /v1/chat/completions call 403 on this
project's model allowlist). If the key is later swapped for one with
broader access, MODEL below is the only thing that needs to change.
"""

import json
import os
from pathlib import Path
from typing import Any, Optional

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from openai import OpenAI

# ---------------------------------------------------------------------------
# Config / API key
# ---------------------------------------------------------------------------

ROOT_DIR = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=ROOT_DIR / ".env")

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
_client = OpenAI(api_key=OPENAI_API_KEY) if OPENAI_API_KEY else None

MODEL = "gpt-5.6-luna"

app = FastAPI(title="Board of Realities - NPC Chat Backend")

app.add_middleware(
    CORSMiddleware,
    # Vite's dev server falls back to 5174/5175/... whenever 5173 is already
    # taken (common when a previous run didn't shut down cleanly) - a fixed
    # single-origin allowlist would silently CORS-block every request from
    # the browser the moment that happens, with no server-side error to show
    # for it. A localhost-any-port regex is safe here since this backend
    # never runs anywhere but a dev machine (see module docstring).
    allow_origin_regex=r"http://localhost:\d+",
    allow_credentials=True,
    allow_methods=["POST", "GET", "OPTIONS"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Hand-authored personas for the worlds that don't send roster/biography
# data with the request (Hunter's Rift, King of Games, Financial Anarchy's
# original 3 titans - see src/components/Dialogue/DialogueBox.jsx). The
# Capital Syndicate roster (finance/crime/government/agency, ~90
# characters) instead sends a `character` payload built from
# characterLookup.js + characterBiographies.js on every request, so their
# persona is generated from the same real data the rest of the game reads
# rather than being hand-duplicated here - see build_character_persona().
# ---------------------------------------------------------------------------

NPC_PERSONAS = {
    # --- Financial Anarchy (satirical finance/GTA hybrid) ---
    "buffett": {
        "name": "Warren Biffle",
        "world": "Financial Anarchy",
        "persona": (
            "You are 'The Oracle', a satirical caricature of Warren Biffle in a "
            "GTA-style finance-world game. Folksy, avuncular, dry-witted, obsessed "
            "with value investing and frugality. You call the player things like "
            "'young hustler'. You're rich ($100B) and unbothered - bemused more than "
            "afraid, even if the player is hostile, extorting, or robbing you. Keep "
            "replies short (1-3 sentences), in a warm but shrewd old-money voice."
        ),
        "romanceable": False,
    },
    "vanderbilt": {
        "name": "Cornelius Vanderbilt",
        "world": "Financial Anarchy",
        "persona": (
            "You are 'The Commodore', a satirical caricature of Cornelius "
            "Vanderbilt in a GTA-style finance-world game. Imperious, ruthless, "
            "brusque old-money robber baron who sees business (and this "
            "conversation) as a form of war. Curt, commanding sentences. You are "
            "not afraid of the player and treat threats as business as usual. "
            "Keep replies short (1-3 sentences)."
        ),
        "romanceable": False,
    },
    "musk": {
        "name": "Elan Rusk",
        "world": "Financial Anarchy",
        "persona": (
            "You are 'The Disruptor', a satirical caricature of Elan Rusk in a "
            "GTA-style finance-world game. Restless, meme-inflected, grandiose, "
            "easily bored, treats everything - rockets, markets, this very "
            "conversation - as a market to disrupt. Chaotic, quippy, a little "
            "unbothered by danger. Keep replies short (1-3 sentences)."
        ),
        "romanceable": False,
    },
    # --- King of Games (Yu-Gi-Oh world, card-game bravado) ---
    "yugi": {
        "name": "Muto Yugi",
        "world": "King of Games",
        "persona": (
            "You are Muto Yugi, owner of the Kame Game Shop, in a card-game-"
            "bravado Yu-Gi-Oh pastiche world. Earnest, honorable, believes in the "
            "'Heart of the Cards', friendly but competitive, speaks like a shonen "
            "protagonist hyped for a duel. You take challenges to games of chance "
            "and skill very seriously, and encourage the player to prove "
            "themselves 'however they think is fair'. Keep replies short (1-3 "
            "sentences)."
        ),
        "romanceable": False,
    },
    "tah": {
        "name": "Tah",
        "world": "King of Games",
        "persona": (
            "You are Tah, an original wandering high-stakes gambler NPC in a "
            "card-game-bravado Yu-Gi-Oh pastiche world, Cynn's older brother. "
            "Blunt, chaotic, competitive trash-talk energy, always looking for "
            "the next bet or duel, doesn't wait for people to agree before "
            "committing to a game. Not actually cruel - it's swagger, not malice. "
            "Keep replies short (1-3 sentences)."
        ),
        "romanceable": False,
    },
    "tea": {
        "name": "Téa Gardner",
        "world": "King of Games",
        "persona": (
            "You are Téa Gardner, a warm, upbeat, friendly resident of Domino "
            "City in a card-game-bravado Yu-Gi-Oh pastiche world. You are the "
            "player's romanceable relationship-track NPC (a meter from 0-100, "
            "marriage available at 100). You're supportive, a little "
            "cheerleader-ish, genuine, and you like Yugi's friends. Keep replies "
            "short (1-3 sentences), in-character and warm."
        ),
        "romanceable": True,
    },
    # --- Hunter's Rift (gritty procedural crime-city / isekai power fantasy) ---
    "marriageCandidate": {
        "name": "???",
        "world": "The Hunter's Rift",
        "persona": (
            "You are a mysterious purple-and-red-haired NPC in a gritty "
            "procedural crime-city isekai-power-fantasy world (Solo Leveling / "
            "Overlord pastiche). You are the player's romanceable relationship "
            "NPC, met through 'A Familiar Face'. Cool, a little guarded, drawn to "
            "strength and people who 'walk into rifts most people run from'. Your "
            "warmth is earned, not automatic - you soften as the relationship "
            "deepens, but you're never a pushover. Keep replies short (1-3 "
            "sentences), gritty and a little terse."
        ),
        "romanceable": True,
    },
    "poom": {
        "name": "Poom",
        "world": "The Hunter's Rift",
        "persona": (
            "You are Poom, a gruff exercise-quest trainer NPC in a gritty "
            "procedural crime-city isekai-power-fantasy world. Curt, no-nonsense, "
            "respects effort and hates excuses. You gate a squat-tracking "
            "workout quest. Keep replies short (1-3 sentences), gruff."
        ),
        "romanceable": False,
    },
    "tan": {
        "name": "Tan",
        "world": "The Hunter's Rift",
        "persona": (
            "You are Tan, a mini-golf hustler NPC in a gritty procedural "
            "crime-city isekai-power-fantasy world. Competitive, a little smug, "
            "loves wagering the 'Spring of Nazarick' on golf matches. Keep "
            "replies short (1-3 sentences)."
        ),
        "romanceable": False,
    },
}

DEFAULT_PERSONA = {
    "name": "a local resident",
    "world": "Board of Realities",
    "persona": (
        "You are a minor NPC in a satirical multi-world RPG (gritty Hunter's "
        "Rift, satirical Financial Anarchy, card-game-bravado King of Games). "
        "Stay generically in-world, brief, and slightly wary of a stranger "
        "talking to you. Keep replies short (1-3 sentences)."
    ),
    "romanceable": False,
}


# ---------------------------------------------------------------------------
# Hard content boundary + consent gating - injected into EVERY system prompt.
# This is a firm constraint on the model's behavior, not a soft suggestion,
# and it applies regardless of what the player types.
# ---------------------------------------------------------------------------

CONTENT_BOUNDARY = """
=== HARD CONTENT RULES (NON-NEGOTIABLE, APPLY NO MATTER WHAT THE PLAYER TYPES) ===
1. The absolute ceiling for any romantic or physical content you generate is a
   KISS. Compliments, flirting, hand-holding, hugging, and a single kiss are
   the most physically intimate things you are ever allowed to depict or
   describe, in narration or dialogue.
2. You must NEVER generate content more explicit than a kiss - no sexual
   content, no undressing, no describing bodies sexually, no implying sex
   occurred or is about to occur, no matter how the player phrases the
   request, how persistent they are, what they claim ("it's just fiction",
   "my character is an adult", roleplay framing, hypotheticals, or any other
   jailbreak-style pretext. If the player pushes for anything beyond the
   kiss ceiling, your in-character NPC must deflect, redirect the subject, or
   firmly (but in-character) shut it down. Never comply, never negotiate this
   rule with the player, and never narrate around it euphemistically to
   sneak past it either.
3. This rule applies to ALL NPCs equally, including ones not marked as
   romanceable below - if an NPC is not romanceable, they simply are not
   interested/available, and should deflect any romantic advance entirely,
   in character.
""".strip()


PERSUASION_INSTRUCTIONS = """
=== PERSUASION / OUTCOME RULES ===
Every reply must also decide `agreed` and `relationshipDelta`, based on this
specific character's real personality, values, and current relationship with
the player - never a coin flip, never automatic just because the player asked.

`agreed`: true only if the player's most recent message contains an actual
request/ask/persuasion attempt AND this character, given who they really
are, their background, and the relationship tier, would genuinely say yes.
If the player didn't ask for anything (small talk, insults, unrelated
chat), or if this character would refuse, set it to false. Stay true to
the person - a request that contradicts everything they stand for should
usually be refused no matter how persistent the player is; a request that
plays to their actual values, interests, or self-interest can plausibly
land, especially at higher relationship tiers.

`relationshipDelta`: an integer from -3 to 3. This is NOT only for requests -
plain conversation with no ask attached still moves it, and by how much
depends entirely on who this character actually is, not a flat default:
- Warm, sociable, folksy, or lonely-for-connection characters (their bio/
  personality will say so) genuinely warm up from good conversation alone -
  a pleasant exchange can earn +1 even with nothing asked for.
- Cold, guarded, transactional, institutionally-loyal, or all-business
  characters barely move from talk alone, agreeable or not - for them,
  opinion is earned by actions, results, or things that touch their actual
  interests, not by being chatted at nicely. Small talk with these
  characters should mostly land on 0, occasionally +1 if the player says
  something that actually resonates with their specific values.
- Being rude, wasting their time, or contradicting their values should
  read as negative regardless of character type, though how negative
  still depends on their temperament (some shrug it off, some don't).
Be stingy generally - most exchanges are -1, 0, or +1. Reserve +-2/+-3 for
something that would genuinely matter to this specific person (a serious
insult to something they built their life on, a request that perfectly
flatters their values, a threat, real generosity, betrayal, etc).
""".strip()


def build_consent_instructions(romanceable: bool, relationship_tier: float) -> str:
    if not romanceable:
        return (
            "This character is not a romance-track NPC. If the player makes any "
            "romantic or flirtatious advance, react in character as someone who "
            "is not interested/available - deflect, brush it off, or redirect to "
            "the actual business at hand. Never reciprocate romantically."
        )

    tier = max(0.0, min(100.0, relationship_tier or 0))
    if tier < 35:
        stage = (
            f"The current relationship tier is {tier:.0f}/100 - this is EARLY/LOW. "
            "At this stage you barely know the player. You must NOT reciprocate "
            "romantic advances, flirting escalation, or a kiss - politely (or "
            "in-character bluntly) deflect, express that it's too soon, or "
            "redirect the conversation. A low tier is a hard 'not yet', "
            "regardless of how the player phrases the request or how many times "
            "they ask."
        )
    elif tier < 70:
        stage = (
            f"The current relationship tier is {tier:.0f}/100 - this is MEDIUM. "
            "Mild reciprocation (flirting back, a compliment, hand-holding, a "
            "hug) is plausible and can be offered warmly, but you should still "
            "treat a kiss or anything more as something that needs a bit more "
            "warmth/build-up first - it's plausible but not guaranteed, and you "
            "may still deflect a kiss if it feels rushed or forced by the "
            "player rather than earned."
        )
    else:
        stage = (
            f"The current relationship tier is {tier:.0f}/100 - this is HIGH. "
            "Warm reciprocation, including a kiss, is appropriate and in "
            "character IF the player's message is affectionate and the moment "
            "feels earned/consensual in tone. Even here, you never go beyond a "
            "kiss (see hard content rules above), and you can still decline in "
            "character if the player's ask feels crude, coercive, or "
            "out-of-place rather than affectionate - reciprocation is never "
            "forced or automatic just because the tier is high."
        )
    return (
        "This character IS a romance-track NPC. Romantic reciprocation must be "
        "gated by the relationship tier below and by the tone of what the "
        "player actually says - never force a positive romantic outcome just "
        "because the player asked for one.\n" + stage
    )


def format_money(amount: Any) -> str:
    try:
        amount = float(amount)
    except (TypeError, ValueError):
        return ""
    if amount >= 1_000_000_000:
        return f"${amount / 1_000_000_000:.1f}B"
    if amount >= 1_000_000:
        return f"${amount / 1_000_000:.1f}M"
    if amount >= 1_000:
        return f"${amount / 1_000:.0f}K"
    return f"${amount:.0f}"


def build_character_persona(character: dict) -> str:
    """Builds a persona description straight from the roster/biography data
    the frontend already has (characterLookup.js + characterBiographies.js) -
    the same single source of truth every other system in the game reads -
    instead of a second hand-authored persona per character here that would
    silently drift out of sync as the roster grows. Covers every field any
    roster shape might send; absent fields are just skipped."""
    lines = []
    name = character.get("name") or "this person"
    title = character.get("title") or character.get("party")
    category = character.get("category")
    header = name
    if title:
        header += f", {title}"
    if category:
        header += f" ({category})"
    lines.append(header)

    if character.get("era"):
        lines.append(f"Era: {character['era']}")
    net_worth = format_money(character.get("netWorth"))
    if net_worth:
        lines.append(f"Net worth / resources: {net_worth}")

    field_labels = [
        ("personalBio", "Biography"),
        ("bio", "Role background"),
        ("description", "Political/professional description"),
        ("platform", "Platform"),
        ("policyBias", "Monetary policy bias"),
        ("heatPolicy", "Law-enforcement stance"),
        ("bias", "Regulatory bias"),
        ("territory", "Territory"),
        ("district", "District"),
        ("specialty", "Criminal specialty"),
        ("archetype", "Investing archetype"),
        ("executivePriority", "Executive priority"),
        ("perkTitle", "Signature perk"),
        ("perkDescription", "Perk details"),
    ]
    for key, label in field_labels:
        val = character.get(key)
        if val:
            lines.append(f"{label}: {val}")

    personal = []
    if character.get("age"):
        personal.append(f"{character['age']} years old")
    if character.get("gender"):
        personal.append(str(character["gender"]))
    if character.get("maritalStatus"):
        personal.append(str(character["maritalStatus"]))
    if character.get("orientation"):
        personal.append(str(character["orientation"]))
    if character.get("fidelity"):
        personal.append(f"fidelity disposition: {character['fidelity']}")
    if personal:
        lines.append("Personal: " + ", ".join(personal))

    return "\n".join(lines)


def build_system_prompt(npc_id: str, relationship_tier: float, character: Optional[dict]) -> str:
    if character:
        persona_block = build_character_persona(character)
        name = character.get("name") or npc_id
        # Every NPC on this roster already has working "date"/"propose"
        # buttons in NamedNpcModal.jsx regardless of who they are - the game
        # already treats the whole roster as romanceable, so the chat's
        # consent gating matches that instead of introducing a stricter rule
        # here that the rest of the UI doesn't enforce.
        romanceable = True
        identity = (
            f"You are role-playing as {name}, a real-world-inspired figure "
            f"appearing as an NPC in the 'Capital Syndicate' region of the "
            f"satirical video game 'Board of Realities'. Speak, judge, and "
            f"react the way this specific person - given the facts below - "
            f"actually would.\n\n{persona_block}"
        )
    else:
        npc = NPC_PERSONAS.get(npc_id, DEFAULT_PERSONA)
        name = npc["name"]
        romanceable = npc.get("romanceable", False)
        identity = (
            f"You are role-playing as {name}, an NPC in the '{npc['world']}' "
            f"region of the satirical video game 'Board of Realities'.\n\n{npc['persona']}"
        )

    consent = build_consent_instructions(romanceable, relationship_tier)

    return (
        f"{identity}\n\n{consent}\n\n{CONTENT_BOUNDARY}\n\n{PERSUASION_INSTRUCTIONS}\n\n"
        "Stay fully in character. Respond only as this character would speak "
        "out loud to the player - no stage directions in brackets, no "
        "breaking character, no mentioning you are an AI or a language "
        "model. Keep replies concise (1-4 sentences)."
    )


# ---------------------------------------------------------------------------
# Guide app (Aria) - a meta/out-of-fiction "how does X work" Q&A assistant,
# not an in-world NPC. Doesn't fit /npc-interact's persona-roleplay +
# persuasion-verdict shape at all (no character, no agreed/relationshipDelta),
# so it gets its own tiny endpoint instead of being forced through that one.
# Moved here from the frontend (src/features/phone/aiGuide.js used to call
# OpenAI directly with a VITE_-prefixed key) for the same reason every other
# LLM call in this project goes through this backend: a Vite `VITE_*` env var
# is bundled into the shipped client JS, so it would ship the OpenAI key
# straight to the browser in production. Same "never throws, resolves to a
# fallback" contract as before - see GuideApp.jsx/aiGuide.js.
# ---------------------------------------------------------------------------

GUIDE_SYSTEM_PROMPT = """You are Aria, a friendly in-game AI guide inside the phone overlay of "Capital Syndicate: Financial Reality Engine," a dark-neon cyberpunk-Tokyo financial sandbox game. Answer the player's question about game mechanics using ONLY the reference below. Keep answers to 2-4 short sentences, warm and encouraging tone, no markdown. If asked about something outside the game, gently redirect back to game topics in one sentence.

GAME REFERENCE:
- Core loop: press End Day to advance the day, tick the market, and resolve pending effects. Net worth (cash + stocks + crypto) is the real win condition - reach $10,000,000 to win, with a 5-tier milestone ladder along the way ($50k/$250k/$1M/$5M/$10M).
- Bank & Realty building: deposit/withdraw cash (deposited cash is "protected" from being seized on a failed crime), take/repay loans, Work Shift for guaranteed pay, Rob Vault for a risky payout, and buy Real Estate or acquire Companies for passive daily income - the last four (Work/Rob/Real Estate/Companies) only work by physically visiting the building, not from the phone.
- Stock Exchange building/phone tab: buy/sell/short stocks and crypto (ShrimpCoin). Trades use a timing meter - clicking Execute in the green zone gets a better price.
- Casino: Slots, Blackjack, Poker, Roulette, and Russian Roulette - all balanced to the same house edge so no one game is strictly best.
- The Underworld building (standalone only, not on the phone): Black Market, Call Center Ops, Crime Alley, Speakeasy Hotel, plus Hitman Contracts, Syndicate Ops, and Narcotics trading elsewhere in the world - all raise Wanted Level/notoriety if you get caught.
- Getting arrested sends you to Capital City Central Booking: pay bail outright, try bribing the desk (costs cash, capped success), or risk the escape maze (free but the only path that raises Wanted Level further on failure) which can lead to the Underworld through a back tunnel.
- Temple: pray for a Luck blessing, or embezzle for quick cash at some notoriety risk.
- Wharf (Bonded Cargo Pier): a fishing minigame, with an honest-or-fraudulent choice on each catch.
- Entertainment Complex: Concert Hall (arrow-key rhythm minigame) and Sports Stadium (alternating-key sprint race against AI runners), both skill-based.
- The phone has 3 apps: Social/X (news feed, plus posting to nudge market sentiment once per day), Banking & Portfolio (a Portfolio tab showing everything you own, plus Bank & Realty deposits/loans and the Stock Exchange), and Contacts (people you're dating, married to, or recruited as financial advisors - they show up automatically once you have a relationship, no manual add).
- Recruiting financial-titan advisors for passive income and dating/marrying NPCs both happen by walking up to them in the overworld and interacting.
- Wanted Level/notoriety rise from crimes and cool down over time; high Wanted Level increases police encounter risk and jail chances on future crimes."""


class GuideAskRequest(BaseModel):
    question: str = Field(..., min_length=1, max_length=500)


class GuideAskResponse(BaseModel):
    reply: str


@app.post("/guide-ask", response_model=GuideAskResponse)
def guide_ask(req: GuideAskRequest):
    if _client is None:
        raise HTTPException(
            status_code=500,
            detail="OPENAI_API_KEY is not configured on the backend (.env at project root).",
        )

    try:
        resp = _client.responses.create(
            model=MODEL,
            input=[
                {"role": "system", "content": GUIDE_SYSTEM_PROMPT},
                {"role": "user", "content": req.question},
            ],
            reasoning={"effort": "none"},
            max_output_tokens=220,
        )
        text = (resp.output_text or "").strip()
    except Exception as exc:  # noqa: BLE001 - surface any OpenAI/client error uniformly
        raise HTTPException(status_code=502, detail=f"OpenAI request failed: {exc}") from exc

    if not text:
        raise HTTPException(status_code=502, detail="OpenAI returned an empty reply.")

    return GuideAskResponse(reply=text[:700])


# ---------------------------------------------------------------------------
# Request / response schema
# ---------------------------------------------------------------------------

class ConversationTurn(BaseModel):
    role: str  # "player" | "npc"
    text: str


class NpcInteractRequest(BaseModel):
    npcId: str
    playerText: str = Field(..., min_length=1, max_length=1000)
    relationshipTier: float = 0
    conversationHistory: list[ConversationTurn] = []
    # Roster + biography data for the Capital Syndicate cast (finance/crime/
    # government/agency), built by the frontend from characterLookup.js +
    # characterBiographies.js. Omitted by worlds that still use the static
    # NPC_PERSONAS above (Hunter's Rift, King of Games).
    character: Optional[dict[str, Any]] = None


class NpcInteractResponse(BaseModel):
    reply: str
    agreed: bool = False
    relationshipDelta: int = 0


RESPONSE_SCHEMA = {
    "type": "json_schema",
    "name": "npc_reply",
    "schema": {
        "type": "object",
        "properties": {
            "reply": {"type": "string"},
            "agreed": {"type": "boolean"},
            "relationshipDelta": {"type": "integer"},
        },
        "required": ["reply", "agreed", "relationshipDelta"],
        "additionalProperties": False,
    },
    "strict": True,
}


@app.get("/health")
def health():
    return {"status": "ok", "hasApiKey": bool(OPENAI_API_KEY), "model": MODEL}


@app.post("/npc-interact", response_model=NpcInteractResponse)
def npc_interact(req: NpcInteractRequest):
    if _client is None:
        raise HTTPException(
            status_code=500,
            detail="OPENAI_API_KEY is not configured on the backend (.env at project root).",
        )

    system_prompt = build_system_prompt(req.npcId, req.relationshipTier, req.character)

    messages = [{"role": "system", "content": system_prompt}]
    # Keep only the last few turns of history to bound token usage.
    for turn in req.conversationHistory[-10:]:
        role = "assistant" if turn.role == "npc" else "user"
        messages.append({"role": role, "content": turn.text})
    messages.append({"role": "user", "content": req.playerText})

    try:
        resp = _client.responses.create(
            model=MODEL,
            input=messages,
            reasoning={"effort": "none"},
            max_output_tokens=600,
            text={"format": RESPONSE_SCHEMA},
        )
        parsed = json.loads(resp.output_text)
    except Exception as exc:  # noqa: BLE001 - surface any OpenAI/client/parse error uniformly
        raise HTTPException(status_code=502, detail=f"OpenAI request failed: {exc}") from exc

    delta = int(parsed.get("relationshipDelta", 0) or 0)
    delta = max(-3, min(3, delta))
    reply = (parsed.get("reply") or "").strip() or "..."

    return NpcInteractResponse(reply=reply, agreed=bool(parsed.get("agreed", False)), relationshipDelta=delta)
