export const FINANCE_NPCS = [
  // --- Ancient & Renaissance Banking Pioneers ---
  {
    id: 'mansamusa',
    name: 'Mansa Musa',
    title: 'The Gold Emperor',
    era: '14th Century',
    archetype: 'sovereign_banker',
    palette: { skin: '#5a3825', hair: '#1a1a1a', outfit: '#ffd700', hairStyle: 'Short' },
    netWorth: 400000000000,
    bodyguardPower: 10,
    recruitCost: 25000,
    perkTitle: 'Gold Sovereign Reserve',
    perkDescription: '+25% cash bonus on all job earnings and transactions.',
  },
  {
    id: 'fugger',
    name: 'Jakob Fugger',
    title: 'The Sovereign Banker',
    era: '15th Century',
    archetype: 'sovereign_banker',
    palette: { skin: '#f1c27d', hair: '#e0e0e0', outfit: '#8b0000', hairStyle: 'Long' },
    netWorth: 300000000000,
    bodyguardPower: 9,
    recruitCost: 20000,
    perkTitle: 'Crown Credit Line',
    perkDescription: 'Provides $800 daily passive revenue from royal loans.',
  },
  {
    id: 'rothschild',
    name: 'Mayer Amschel Rothschild',
    title: 'The Dynasty Founder',
    era: '18th Century',
    archetype: 'sovereign_banker',
    palette: { skin: '#f1c27d', hair: '#8a8a8a', outfit: '#1b365d', hairStyle: 'Short' },
    netWorth: 350000000000,
    bodyguardPower: 9,
    recruitCost: 22000,
    perkTitle: 'Courier Intelligence',
    perkDescription: 'Increases market news accuracy & insider trade payout by +30%.',
  },
  {
    id: 'hamilton',
    name: 'Alexander Hamilton',
    title: 'The Treasury Architect',
    era: '18th Century',
    archetype: 'sovereign_banker',
    palette: { skin: '#e0ac69', hair: '#ffffff', outfit: '#00205b', hairStyle: 'Long' },
    netWorth: 50000000,
    bodyguardPower: 6,
    recruitCost: 5000,
    perkTitle: 'Federal Heat Immunity',
    perkDescription: 'Automatically reduces Wanted Level by 1 every 2 days.',
  },

  // --- Gilded Age Industrial & Railroad Titans ---
  {
    id: 'vanderbilt',
    name: 'Cornelius Vanderbilt',
    title: 'The Commodore',
    era: 'Gilded Age',
    archetype: 'monopolist',
    palette: { skin: '#e0ac69', hair: '#e0e0e0', outfit: '#5a3825', hairStyle: 'Long' },
    netWorth: 200000000000,
    bodyguardPower: 8,
    recruitCost: 15000,
    perkTitle: 'Railroad Logistics Squeeze',
    perkDescription: 'Adds +$600 daily shipping toll revenue.',
  },
  {
    id: 'rockefeller',
    name: 'John D. Rockefeller',
    title: 'The Standard Monopolist',
    era: 'Gilded Age',
    archetype: 'monopolist',
    palette: { skin: '#f1c27d', hair: '#a0a0a0', outfit: '#1c1c1c', hairStyle: 'Short' },
    netWorth: 400000000000,
    bodyguardPower: 10,
    recruitCost: 30000,
    perkTitle: 'Standard Monopoly Squeeze',
    perkDescription: 'Increases revenue from all owned real estate & companies by +35%.',
  },
  {
    id: 'carnegie',
    name: 'Andrew Carnegie',
    title: 'The Steel Titan',
    era: 'Gilded Age',
    archetype: 'monopolist',
    palette: { skin: '#f1c27d', hair: '#ffffff', outfit: '#3b2f2f', hairStyle: 'Buzzcut' },
    netWorth: 310000000000,
    bodyguardPower: 8,
    recruitCost: 18000,
    perkTitle: 'Bessemer Scale Efficiency',
    perkDescription: '+20% EXP gain and grants a $5,000 philanthropic grant upon recruitment.',
  },
  {
    id: 'jpmorgan',
    name: 'J.P. Morgan',
    title: 'The Syndicate Commodore',
    era: 'Gilded Age',
    archetype: 'monopolist',
    palette: { skin: '#e0ac69', hair: '#c0c0c0', outfit: '#0a0a23', hairStyle: 'Short' },
    netWorth: 200000000000,
    bodyguardPower: 9,
    recruitCost: 20000,
    perkTitle: 'Consolidation Bailout',
    perkDescription: 'Instantly grants $10,000 emergency cash if cash drops below $500.',
  },
  {
    id: 'ford',
    name: 'Henry Ford',
    title: 'The Mass Producer',
    era: 'Early 20th Century',
    archetype: 'monopolist',
    palette: { skin: '#f1c27d', hair: '#808080', outfit: '#2c3e50', hairStyle: 'Short' },
    netWorth: 200000000000,
    bodyguardPower: 7,
    recruitCost: 12000,
    perkTitle: 'Assembly Line Wage Engine',
    perkDescription: 'Generates $500 automated passive income every single day.',
  },
  {
    id: 'walker',
    name: 'Madam C.J. Walker',
    title: 'The Grassroots Pioneer',
    era: 'Early 20th Century',
    archetype: 'monopolist',
    palette: { skin: '#4a2c11', hair: '#1a1a1a', outfit: '#6a1b9a', hairStyle: 'Long' },
    netWorth: 10000000,
    bodyguardPower: 5,
    recruitCost: 4000,
    perkTitle: 'Grassroots Agent Network',
    perkDescription: 'Boosts Public Reputation by +20 and yields $300 daily network royalties.',
  },

  // --- Value Investors & Market Operators ---
  {
    id: 'graham',
    name: 'Benjamin Graham',
    title: 'The Father of Value',
    era: 'Mid 20th Century',
    archetype: 'value_investor',
    palette: { skin: '#f1c27d', hair: '#d3d3d3', outfit: '#34495e', hairStyle: 'Short' },
    netWorth: 100000000,
    bodyguardPower: 4,
    recruitCost: 6000,
    perkTitle: 'Margin of Safety Shield',
    perkDescription: 'Protects portfolio stocks from crashing more than 10% in a single day.',
  },
  {
    id: 'livermore',
    name: 'Jesse Livermore',
    title: 'The Great Bear',
    era: 'Mid 20th Century',
    archetype: 'macro_speculator',
    palette: { skin: '#e0ac69', hair: '#4a4a4a', outfit: '#111111', hairStyle: 'Short' },
    netWorth: 100000000,
    bodyguardPower: 7,
    recruitCost: 8000,
    perkTitle: 'Bear Raid Leverage',
    perkDescription: '+50% cash payout when stock market trends downward.',
  },
  {
    id: 'templeton',
    name: 'Sir John Templeton',
    title: 'The Global Contrarian',
    era: 'Late 20th Century',
    archetype: 'value_investor',
    palette: { skin: '#f1c27d', hair: '#f0f0f0', outfit: '#1e3d59', hairStyle: 'Short' },
    netWorth: 5000000000,
    bodyguardPower: 5,
    recruitCost: 7500,
    perkTitle: 'Maximum Pessimism Arbitrage',
    perkDescription: 'Buys crypto dip automatically, granting +30% crypto profit multipliers.',
  },
  {
    id: 'buffett',
    name: 'Warren Biffle',
    title: 'The Oracle of Omaha',
    era: 'Modern',
    archetype: 'value_investor',
    palette: { skin: '#f1c27d', hair: '#e0e0e0', outfit: '#333333', hairStyle: 'Short' },
    netWorth: 130000000000,
    bodyguardPower: 6,
    recruitCost: 15000,
    perkTitle: 'Economic Moat Compounding',
    perkDescription: 'Earns 5% daily compounding interest on all cash holdings.',
  },
  {
    id: 'howardmarks',
    name: 'Howard Marks',
    title: 'The Cycle Philosopher',
    era: 'Modern',
    archetype: 'value_investor',
    palette: { skin: '#e8c898', hair: '#c0c0c0', outfit: '#2a4f4a', hairStyle: 'Short' },
    netWorth: 2200000000,
    bodyguardPower: 5,
    recruitCost: 8500,
    perkTitle: 'Market Cycle Mastery',
    perkDescription: 'Grants a 20% chance to dodge losses entirely on the next market downturn.',
  },
  {
    id: 'munger',
    name: 'Charlie Munger',
    title: 'The Polymath Strategist',
    era: 'Modern',
    archetype: 'value_investor',
    palette: { skin: '#e0ac69', hair: '#cccccc', outfit: '#2c2c54', hairStyle: 'Short' },
    netWorth: 2500000000,
    bodyguardPower: 5,
    recruitCost: 9000,
    perkTitle: 'Multidisciplinary Inversion',
    perkDescription: 'Reduces job cooldown timer by 50% and enhances reputation gains.',
  },
  {
    id: 'lynch',
    name: 'Peter Vance',
    title: 'The 10-Bagger Hunter',
    era: 'Modern',
    archetype: 'value_investor',
    palette: { skin: '#f1c27d', hair: '#ffffff', outfit: '#27ae60', hairStyle: 'Short' },
    netWorth: 500000000,
    bodyguardPower: 4,
    recruitCost: 5000,
    perkTitle: 'Everyday Consumer Radar',
    perkDescription: 'Triggers random 10-Bagger stock surges in the market.',
  },

  // --- Macro & Quant Masters ---
  {
    id: 'soros',
    name: 'George Zoros',
    title: 'The Reflexive Sorcerer',
    era: 'Modern',
    archetype: 'macro_speculator',
    palette: { skin: '#f1c27d', hair: '#dcdcdc', outfit: '#4a154b', hairStyle: 'Short' },
    netWorth: 10000000000,
    bodyguardPower: 8,
    recruitCost: 16000,
    perkTitle: 'Reflexivity Currency Raid',
    perkDescription: 'Ability to force market volatility, generating $1,200 on market moves.',
  },
  {
    id: 'dalio',
    name: 'Ray Daglio',
    title: 'The Macro Architect',
    era: 'Modern',
    archetype: 'macro_speculator',
    palette: { skin: '#e0ac69', hair: '#a9a9a9', outfit: '#2c3e50', hairStyle: 'Short' },
    netWorth: 19000000000,
    bodyguardPower: 7,
    recruitCost: 14000,
    perkTitle: 'All-Weather Risk Parity',
    perkDescription: 'Mitigates all market drop losses by 50%.',
  },
  {
    id: 'simons',
    name: 'Jim Simons',
    title: 'The Quant Mastermind',
    era: 'Modern',
    archetype: 'macro_speculator',
    palette: { skin: '#f1c27d', hair: '#ffffff', outfit: '#16a085', hairStyle: 'Short' },
    netWorth: 30000000000,
    bodyguardPower: 8,
    recruitCost: 18000,
    perkTitle: 'Medallion High-Frequency Algo',
    perkDescription: 'Generates $1,000 automated algorithmic trading profit every day.',
  },
  {
    id: 'icahn',
    name: 'Karl Eikahn',
    title: 'The Corporate Raider',
    era: 'Modern',
    archetype: 'corporate_raider',
    palette: { skin: '#e0ac69', hair: '#95a5a6', outfit: '#c0392b', hairStyle: 'Short' },
    netWorth: 18000000000,
    bodyguardPower: 8,
    recruitCost: 15000,
    perkTitle: 'Hostile Board Squeeze',
    perkDescription: 'Grants a 25% discount when purchasing companies.',
  },

  // --- Modern Tech Titans & Visionaries ---
  {
    id: 'jobs',
    name: 'Steve Jobs',
    title: 'The Design Visionary',
    era: 'Modern',
    archetype: 'tech_disruptor',
    palette: { skin: '#f1c27d', hair: '#7f8c8d', outfit: '#000000', hairStyle: 'Short' },
    netWorth: 10000000000,
    bodyguardPower: 6,
    recruitCost: 12000,
    perkTitle: 'Reality Distortion Field',
    perkDescription: '+30% bonus on all product sales & company valuations.',
  },
  {
    id: 'gates',
    name: 'Will Gatling',
    title: 'The Software Standard',
    era: 'Modern',
    archetype: 'tech_disruptor',
    palette: { skin: '#f1c27d', hair: '#bdc3c7', outfit: '#2980b9', hairStyle: 'Short' },
    netWorth: 120000000000,
    bodyguardPower: 7,
    recruitCost: 16000,
    perkTitle: 'OS Software Royalty Engine',
    perkDescription: 'Collects $850 in software license royalties every day.',
  },
  {
    id: 'bezos',
    name: 'Geoff Bezel',
    title: 'The Scale Engine',
    era: 'Modern',
    archetype: 'tech_disruptor',
    palette: { skin: '#f1c27d', hair: '#f1c27d', outfit: '#2c3e50', hairStyle: 'Buzzcut' },
    netWorth: 200000000000,
    bodyguardPower: 9,
    recruitCost: 20000,
    perkTitle: 'AWS & Logistics Empire',
    perkDescription: 'Generates $1,200 daily cloud revenue and unlocks infinite storage.',
  },
  {
    id: 'musk',
    name: 'Elan Rusk',
    title: 'The Technoking Disrupter',
    era: 'Modern',
    archetype: 'tech_disruptor',
    palette: { skin: '#f1c27d', hair: '#1a1a1a', outfit: '#3f6fd6', hairStyle: 'Short' },
    netWorth: 250000000000,
    bodyguardPower: 10,
    recruitCost: 25000,
    perkTitle: 'Crypto Rocket Launcher',
    perkDescription: 'Boosts crypto hype by +25 and generates high-volatility trading events.',
  },
  {
    id: 'huang',
    name: 'Jensen Fang',
    title: 'The AI Compute Architect',
    era: 'Modern',
    archetype: 'tech_disruptor',
    palette: { skin: '#e0ac69', hair: '#1a1a1a', outfit: '#111111', hairStyle: 'Short' },
    netWorth: 110000000000,
    bodyguardPower: 9,
    recruitCost: 22000,
    perkTitle: 'GPU Parallel Compute Engine',
    perkDescription: 'Predicts exact stock price movements for the next day.',
  },
  {
    id: 'son',
    name: 'Masatoshi Ren',
    title: 'The Visionary Risk Taker',
    era: 'Modern',
    archetype: 'tech_disruptor',
    palette: { skin: '#f1c27d', hair: '#7f8c8d', outfit: '#8e44ad', hairStyle: 'Short' },
    netWorth: 30000000000,
    bodyguardPower: 7,
    recruitCost: 15000,
    perkTitle: 'Vision Fund Seed Injection',
    perkDescription: 'Instantly provides a $15,000 high-risk venture capital injection.',
  },
]

export function getFinanceNpc(id) {
  return FINANCE_NPCS.find((n) => n.id === id)
}

export function generateBodyguardMonster(npc) {
  const hp = 80 + npc.bodyguardPower * 30
  const atk = 8 + npc.bodyguardPower * 3
  return {
    name: `${npc.name}'s Elite Retainer Guard`,
    maxHp: Math.round(hp),
    hp: Math.round(hp),
    attack: Math.round(atk),
  }
}

export function generateStreetTargetMonster() {
  return {
    name: 'Panicking Bystander',
    maxHp: 20,
    hp: 20,
    attack: 3,
  }
}

export function generateSwatSquad(wantedLevel) {
  const unit = wantedLevel >= 4 ? 'FBI Tactical Unit' : 'SWAT Squad'
  const scale = wantedLevel
  const hp = 70 + scale * 12
  const atk = 9 + scale * 2.2
  return {
    name: unit,
    maxHp: Math.round(hp),
    hp: Math.round(hp),
    attack: Math.round(atk),
  }
}
