// 7 Historical Crime Syndicates with 21 Autonomous Agents (Boss, Underboss, Capo)

export const CRIME_SYNDICATES = [
  {
    id: 'chicago_outfit',
    name: 'The Chicago Outfit',
    territory: 'Underground District - West',
    palette: { skin: '#e0ac69', hair: '#1a1a1a', outfit: '#1a1a2e', hairStyle: 'Short' }, // Capone: dark Italian-American look, dark navy suit
    boss: { id: 'capone', name: 'Al Capone', title: 'Scarface (Boss)', aggression: 0.9, extortionPower: 2500,
      palette: { skin: '#e0ac69', hair: '#1a1a1a', outfit: '#1a1a2e', hairStyle: 'Short' } },
    underboss: { id: 'nitti', name: 'Frank Nitti', title: 'The Enforcer (Underboss)', aggression: 0.8,
      palette: { skin: '#d4956a', hair: '#222222', outfit: '#2a1a1a', hairStyle: 'Buzzcut' } },
    capo: { id: 'ricca', name: 'Paul Ricca', title: 'The Brain (Capo)', aggression: 0.6,
      palette: { skin: '#e0c090', hair: '#333333', outfit: '#1c2438', hairStyle: 'Short' } },
    specialty: 'Bootleg Speakeasy & Extortion Squeeze',
    dailyToll: 1200,
  },
  {
    id: 'five_families',
    name: 'The Five Families (Luciano Family)',
    territory: 'Commercial District - Docks',
    palette: { skin: '#f1c27d', hair: '#333333', outfit: '#1b365d', hairStyle: 'Short' }, // Luciano: sharp Italian, navy pinstripe
    boss: { id: 'luciano', name: 'Lucky Luciano', title: 'The Commission Founder (Boss)', aggression: 0.85, extortionPower: 3000,
      palette: { skin: '#f1c27d', hair: '#333333', outfit: '#1b365d', hairStyle: 'Short' } },
    underboss: { id: 'genovese', name: 'Vito Genovese', title: 'The Don (Underboss)', aggression: 0.9,
      palette: { skin: '#e8c090', hair: '#444444', outfit: '#1a1a3e', hairStyle: 'Short' } },
    capo: { id: 'costello', name: 'Frank Costello', title: 'The Prime Minister (Consigliere)', aggression: 0.5,
      palette: { skin: '#f0d4a0', hair: '#555555', outfit: '#2d2d2d', hairStyle: 'Short' } },
    specialty: 'National Crime Commission & Dock Rackets',
    dailyToll: 1500,
  },
  {
    id: 'national_syndicate',
    name: 'The National Crime Syndicate',
    territory: 'Financial District - Vaults',
    palette: { skin: '#f1c27d', hair: '#8a8a8a', outfit: '#111111', hairStyle: 'Short' }, // Lansky: pale, grey-haired accountant look
    boss: { id: 'lansky', name: 'Meyer Lansky', title: 'The Mob Accountant (Boss)', aggression: 0.4, extortionPower: 4000,
      palette: { skin: '#f1c27d', hair: '#8a8a8a', outfit: '#111111', hairStyle: 'Short' } },
    underboss: { id: 'siegel', name: 'Bugsy Siegel', title: 'The Flamingo Builder (Underboss)', aggression: 0.95,
      palette: { skin: '#f0d4a0', hair: '#1a1a1a', outfit: '#1e1e1e', hairStyle: 'Short' } },
    capo: { id: 'cohen', name: 'Mickey Cohen', title: 'West Coast Capo', aggression: 0.85,
      palette: { skin: '#e8c890', hair: '#222222', outfit: '#222244', hairStyle: 'Buzzcut' } },
    specialty: 'High-Stakes Casino Skimming & Offshore Banking',
    dailyToll: 2000,
  },
  {
    id: 'medellin_cartel',
    name: 'The Medellin Syndicate',
    territory: 'Underground District - Docks',
    palette: { skin: '#b07040', hair: '#1a1a1a', outfit: '#8b0000', hairStyle: 'Short' }, // Escobar: Colombian, dark red Colombian shirt
    boss: { id: 'escobar', name: 'Pablo Escobar', title: 'El Patron (Boss)', aggression: 0.95, extortionPower: 5000,
      palette: { skin: '#b07040', hair: '#1a1a1a', outfit: '#8b0000', hairStyle: 'Short' } },
    underboss: { id: 'gaviria', name: 'Gustavo Gaviria', title: 'The Strategist (Underboss)', aggression: 0.75,
      palette: { skin: '#b86828', hair: '#222222', outfit: '#2a1000', hairStyle: 'Short' } },
    capo: { id: 'ochoa', name: 'Jorge Ochoa', title: 'The Financier (Capo)', aggression: 0.5,
      palette: { skin: '#c07840', hair: '#333333', outfit: '#1a2010', hairStyle: 'Short' } },
    specialty: 'Global Smuggling & Bribes',
    dailyToll: 2500,
  },
  {
    id: 'griselda_empire',
    name: 'The Griselda Empire',
    territory: 'Commercial District - Nightlife',
    palette: { skin: '#b07040', hair: '#1a1a1a', outfit: '#4a1f6a', hairStyle: 'Long' }, // Blanco: Latina woman, purple luxury dress
    boss: { id: 'blanco', name: 'Griselda Blanco', title: 'The Black Widow (Boss)', aggression: 0.98, extortionPower: 3500,
      palette: { skin: '#b07040', hair: '#1a1a1a', outfit: '#4a1f6a', hairStyle: 'Long' } },
    underboss: { id: 'osvaldo', name: 'Osvaldo Trujillo', title: 'Cartel Prince (Underboss)', aggression: 0.85,
      palette: { skin: '#b07848', hair: '#222222', outfit: '#2a1050', hairStyle: 'Short' } },
    capo: { id: 'dixon', name: 'Dixon Trujillo', title: 'Nightlife Capo', aggression: 0.8,
      palette: { skin: '#b88050', hair: '#333333', outfit: '#1a0828', hairStyle: 'Short' } },
    specialty: 'Ruthless Turf Dominance & Nightclub Rackets',
    dailyToll: 1800,
  },
  {
    id: 'murder_inc',
    name: 'Murder Inc.',
    territory: 'Underground District - Alleyways',
    palette: { skin: '#d3d3d3', hair: '#1a1a1a', outfit: '#1c1c1c', hairStyle: 'Buzzcut' }, // Lepke: pale Jewish gangster
    boss: { id: 'lepke', name: 'Lepke Buchalter', title: 'The Industrial Extortionist (Boss)', aggression: 0.9, extortionPower: 2800,
      palette: { skin: '#d0c0a0', hair: '#1a1a1a', outfit: '#1c1c1c', hairStyle: 'Buzzcut' } },
    underboss: { id: 'anastasia', name: 'Albert Anastasia', title: 'Lord High Executioner (Underboss)', aggression: 1.0,
      palette: { skin: '#d4b890', hair: '#222222', outfit: '#111111', hairStyle: 'Short' } },
    capo: { id: 'weiss', name: 'Mendy Weiss', title: 'Hit Squad Leader (Capo)', aggression: 0.95,
      palette: { skin: '#d8c0a0', hair: '#333333', outfit: '#0a0a0a', hairStyle: 'Short' } },
    specialty: 'Contract Assassinations & Garment Racketeering',
    dailyToll: 1400,
  },
  {
    id: 'speakeasy_syndicate',
    name: 'The Speakeasy Syndicate',
    territory: 'Government & Cultural District',
    palette: { skin: '#f1c27d', hair: '#ffffff', outfit: '#3b2f2f', hairStyle: 'Long' }, // Rothstein: pale fixer, dark brown
    boss: { id: 'rothstein', name: 'Arnold Rothstein', title: 'The Brain / Fixer (Boss)', aggression: 0.3, extortionPower: 3200,
      palette: { skin: '#f0d4a0', hair: '#dddddd', outfit: '#3b2f2f', hairStyle: 'Short' } },
    underboss: { id: 'waxey', name: 'Waxey Gordon', title: 'Rum Runner (Underboss)', aggression: 0.7,
      palette: { skin: '#e8c890', hair: '#444444', outfit: '#2c2c2c', hairStyle: 'Short' } },
    capo: { id: 'remus', name: 'George Remus', title: 'Bootleg King (Capo)', aggression: 0.5,
      palette: { skin: '#f0d090', hair: '#888888', outfit: '#2a2010', hairStyle: 'Short' } },
    specialty: 'High-Level Political Fixing & World Series Gambling',
    dailyToll: 1600,
  },
]
