// 7 Historical Crime Syndicates with 21 Autonomous Agents (Boss, Underboss, Capo)

export const CRIME_SYNDICATES = [
  {
    id: 'chicago_outfit',
    name: 'The Chicago Outfit',
    territory: 'Underground District - West',
    palette: { skin: '#e0ac69', hair: '#1a1a1a', outfit: '#2c3e50', hairStyle: 'Short' },
    boss: { id: 'capone', name: 'Al Capone', title: 'Scarface (Boss)', aggression: 0.9, extortionPower: 2500 },
    underboss: { id: 'nitti', name: 'Frank Nitti', title: 'The Enforcer (Underboss)', aggression: 0.8 },
    capo: { id: 'ricca', name: 'Paul Ricca', title: 'The Brain (Capo)', aggression: 0.6 },
    specialty: 'Bootleg Speakeasy & Extortion Squeeze',
    dailyToll: 1200,
  },
  {
    id: 'five_families',
    name: 'The Five Families (Luciano Family)',
    territory: 'Commercial District - Docks',
    palette: { skin: '#f1c27d', hair: '#333333', outfit: '#1b365d', hairStyle: 'Short' },
    boss: { id: 'luciano', name: 'Lucky Luciano', title: 'The Commission Founder (Boss)', aggression: 0.85, extortionPower: 3000 },
    underboss: { id: 'genovese', name: 'Vito Genovese', title: 'The Don (Underboss)', aggression: 0.9 },
    capo: { id: 'costello', name: 'Frank Costello', title: 'The Prime Minister (Consigliere)', aggression: 0.5 },
    specialty: 'National Crime Commission & Dock Rackets',
    dailyToll: 1500,
  },
  {
    id: 'national_syndicate',
    name: 'The National Crime Syndicate',
    territory: 'Financial District - Vaults',
    palette: { skin: '#f1c27d', hair: '#8a8a8a', outfit: '#111111', hairStyle: 'Short' },
    boss: { id: 'lansky', name: 'Meyer Lansky', title: 'The Mob Accountant (Boss)', aggression: 0.4, extortionPower: 4000 },
    underboss: { id: 'siegel', name: 'Bugsy Siegel', title: 'The Flamingo Builder (Underboss)', aggression: 0.95 },
    capo: { id: 'cohen', name: 'Mickey Cohen', title: 'West Coast Capo', aggression: 0.85 },
    specialty: 'High-Stakes Casino Skimming & Offshore Banking',
    dailyToll: 2000,
  },
  {
    id: 'medellin_cartel',
    name: 'The Medellin Syndicate',
    territory: 'Underground District - Docks',
    palette: { skin: '#e0ac69', hair: '#1a1a1a', outfit: '#8b0000', hairStyle: 'Short' },
    boss: { id: 'escobar', name: 'Pablo Escobar', title: 'El Patron (Boss)', aggression: 0.95, extortionPower: 5000 },
    underboss: { id: 'gaviria', name: 'Gustavo Gaviria', title: 'The Strategist (Underboss)', aggression: 0.75 },
    capo: { id: 'ochoa', name: 'Jorge Ochoa', title: 'The Financier (Capo)', aggression: 0.5 },
    specialty: 'Global Smuggling & Bribes',
    dailyToll: 2500,
  },
  {
    id: 'griselda_empire',
    name: 'The Griselda Empire',
    territory: 'Commercial District - Nightlife',
    palette: { skin: '#e0ac69', hair: '#1a1a1a', outfit: '#4a1f6a', hairStyle: 'Long' },
    boss: { id: 'blanco', name: 'Griselda Blanco', title: 'The Black Widow (Boss)', aggression: 0.98, extortionPower: 3500 },
    underboss: { id: 'osvaldo', name: 'Osvaldo Trujillo', title: 'Cartel Prince (Underboss)', aggression: 0.85 },
    capo: { id: 'dixon', name: 'Dixon Trujillo', title: 'Nightlife Capo', aggression: 0.8 },
    specialty: 'Ruthless Turf Dominance & Nightclub Rackets',
    dailyToll: 1800,
  },
  {
    id: 'murder_inc',
    name: 'Murder Inc.',
    territory: 'Underground District - Alleyways',
    palette: { skin: '#d3d3d3', hair: '#1a1a1a', outfit: '#1c1c1c', hairStyle: 'Buzzcut' },
    boss: { id: 'lepke', name: 'Lepke Buchalter', title: 'The Industrial Extortionist (Boss)', aggression: 0.9, extortionPower: 2800 },
    underboss: { id: 'anastasia', name: 'Albert Anastasia', title: 'Lord High Executioner (Underboss)', aggression: 1.0 },
    capo: { id: 'weiss', name: 'Mendy Weiss', title: 'Hit Squad Leader (Capo)', aggression: 0.95 },
    specialty: 'Contract Assassinations & Garment Racketeering',
    dailyToll: 1400,
  },
  {
    id: 'speakeasy_syndicate',
    name: 'The Speakeasy Syndicate',
    territory: 'Government & Cultural District',
    palette: { skin: '#f1c27d', hair: '#ffffff', outfit: '#3b2f2f', hairStyle: 'Long' },
    boss: { id: 'rothstein', name: 'Arnold Rothstein', title: 'The Brain / Fixer (Boss)', aggression: 0.3, extortionPower: 3200 },
    underboss: { id: 'waxey', name: 'Waxey Gordon', title: 'Rum Runner (Underboss)', aggression: 0.7 },
    capo: { id: 'remus', name: 'George Remus', title: 'Bootleg King (Capo)', aggression: 0.5 },
    specialty: 'High-Level Political Fixing & World Series Gambling',
    dailyToll: 1600,
  },
]
