/**
 * Physical Government Locations, Chambers & Jurisdictional Facilities Catalog.
 */

export const GOVERNMENT_LOCATIONS = [
  {
    id: 'scotus_courtroom',
    name: 'Supreme Court (SCOTUS) Trial Courtroom',
    city: 'Tokyo',
    district: 'Tokyo Judicial District',
    jurisdiction: 'Constitutional Judicial Review & Legal Appeals',
    presidingHead: 'John Marshall & Earl Warren',
    modalType: 'scotusTrial',
    description: 'Neoclassical Marble Citadel where Supreme Court Justices hear constitutional appeals and strike down illegal FTC/SEC fines.',
  },
  {
    id: 'congress_capitol',
    name: 'US Congress Capitol Committee Chamber',
    city: 'Tokyo',
    district: 'Tokyo Capitol District',
    jurisdiction: 'Federal Tax Legislation & Nominee Confirmations',
    presidingHead: 'Henry Clay & Sam Rayburn',
    modalType: 'congressHearing',
    description: 'Domed Capitol Chamber where Representatives vote on tax bills and hold Fed/FTC confirmation hearings.',
  },
  {
    id: 'fed_depository_hq',
    name: 'Federal Reserve Central Bank Vault HQ',
    city: 'Tokyo',
    district: 'Tokyo Financial District',
    jurisdiction: 'Monetary Policy & Interest Rate Controls',
    presidingHead: 'Jerome Powell & Paul Volcker',
    modalType: 'fedControl',
    description: 'High-security granite vault managing benchmark rate adjustments and liquidity injections.',
  },
  {
    id: 'ftc_hearing_commission',
    name: 'FTC Antitrust Hearing Commission',
    city: 'Tokyo',
    district: 'Tokyo Commercial District',
    jurisdiction: 'Monopoly Dissolution & Merger Audits',
    presidingHead: 'Lina Khan',
    modalType: 'ftcHearing',
    description: 'Hearing room where FTC Commissioners audit monopoly conglomerates and issue breakup orders.',
  },
  {
    id: 'treasury_mint_building',
    name: 'US Treasury Building & Federal Mint',
    city: 'Kyoto',
    district: 'Kyoto Financial District',
    jurisdiction: 'National Debt Management & 10-Year Bond Issuance',
    presidingHead: 'Alexander Hamilton',
    modalType: 'treasuryBonds',
    description: 'Historic Treasury Depository issuing 10-Year US Treasury Bonds at guaranteed yields.',
  },
  {
    id: 'irs_audit_building',
    name: 'IRS Internal Revenue Audit Building',
    city: 'Kyoto',
    district: 'Kyoto Historic District',
    jurisdiction: 'High Wealth Audits & Criminal Tax Investigations',
    presidingHead: 'Mortimer Caplin',
    modalType: 'irsAudit',
    description: 'High-security tax audit facility where IRS CID Special Agents investigate wealth tax evasion.',
  },
  {
    id: 'fbi_detention_vault',
    name: 'FBI Bureau Detention & Interrogation Vault',
    city: 'Osaka',
    district: 'Osaka Commercial District',
    jurisdiction: 'Federal Criminal Wiretaps & RICO Arrests',
    presidingHead: 'J. Edgar Hoover',
    modalType: 'fbiInterrogation',
    description: 'Fortified FBI Citadel holding suspects under RICO indictments and federal wiretaps.',
  },
  {
    id: 'pentagon_dod_arsenal',
    name: 'Pentagon / DOD Military Procurement HQ',
    city: 'Sapporo',
    district: 'Sapporo Industrial District',
    jurisdiction: 'DARPA Defense Procurement & Military Grants',
    presidingHead: 'Robert McNamara',
    modalType: 'dodProcurement',
    description: 'Pentagon defense facility awarding military hardware contracts and DARPA grants.',
  },
  {
    id: 'epa_regulation_facility',
    name: 'EPA Environmental Regulation Facility',
    city: 'Sapporo',
    district: 'Sapporo Alpine Region',
    jurisdiction: 'Industrial Clean Air/Water Compliance & Factory Audits',
    presidingHead: 'William Ruckelshaus',
    modalType: 'epaInspection',
    description: 'Environmental monitoring facility inspecting steel mills, refineries, and chemical plants.',
  },
]
