// 10 US Presidents, 10 Federal Reserve Chairmen, 10 FTC Chairmen

export const PRESIDENTS_ROSTER = [
  {
    id: 'washington',
    name: 'George Washington',
    party: 'Independent / Federalist',
    platform: 'National Stability & Public Credit',
    taxRate: 10,
    heatPolicy: 'Strict Law & Order',
    description: 'Establishes federal credit, reduces Wanted Level by granting Presidential Pardons.',
    executivePriority: 'credit_stability',
  },
  {
    id: 'lincoln',
    name: 'Abraham Lincoln',
    party: 'Republican / Union',
    platform: 'Union Infrastructure & Industrial Growth',
    taxRate: 12,
    heatPolicy: 'Union Defense',
    description: 'Subsidizes company & real estate revenues while maintaining federal unity.',
    executivePriority: 'infrastructure_growth',
  },
  {
    id: 'fdr',
    name: 'Franklin D. Roosevelt',
    party: 'Democrat',
    platform: 'New Deal Fiscal Stimulus & Public Works',
    taxRate: 25,
    heatPolicy: 'SEC Oversight',
    description: 'Injects daily public works stimulus cash to all players & businesses.',
    executivePriority: 'fiscal_stimulus',
  },
  {
    id: 'jfk',
    name: 'John F. Kennedy',
    party: 'Democrat',
    platform: 'New Frontier Innovation & Space Grants',
    taxRate: 18,
    heatPolicy: 'Federal Investigation',
    description: 'Grants tech & innovation subsidies, boosting stock & crypto hype.',
    executivePriority: 'tech_grants',
  },
  {
    id: 'reagan',
    name: 'Ronald Reagan',
    party: 'Republican',
    platform: 'Supply-Side Tax Cuts & Deregulation',
    taxRate: 8,
    heatPolicy: 'Free Market Liberty',
    description: 'Cuts taxes to 8% and boosts corporate dividend yields.',
    executivePriority: 'deregulation',
  },
  {
    id: 'tr',
    name: 'Theodore Roosevelt',
    party: 'Progressive / Bull Moose',
    platform: 'Trust-Busting & Monopoly Dissolution',
    taxRate: 20,
    heatPolicy: 'Square Deal Enforcement',
    description: 'Orders aggressive FTC trust-busting against major monopolists.',
    executivePriority: 'trust_busting',
  },
  {
    id: 'jefferson',
    name: 'Thomas Jefferson',
    party: 'Democratic-Republican',
    platform: 'Free Trade & Agrarian Decentralization',
    taxRate: 5,
    heatPolicy: 'State Autonomy',
    description: 'Lowers federal taxes to 5% and limits central government intervention.',
    executivePriority: 'free_trade',
  },
  {
    id: 'eisenhower',
    name: 'Dwight D. Eisenhower',
    party: 'Republican',
    platform: 'Interstate Commerce & Military Logistics',
    taxRate: 15,
    heatPolicy: 'Strategic Defense',
    description: 'Drives commercial real estate value and logistics revenue.',
    executivePriority: 'interstate_commerce',
  },
  {
    id: 'obama',
    name: 'Barack Obama',
    party: 'Democrat',
    platform: 'Clean Energy Grants & Wall Street Reform',
    taxRate: 22,
    heatPolicy: 'Dodd-Frank Compliance',
    description: 'Imposes financial reform oversight while granting green energy subsidies.',
    executivePriority: 'financial_reform',
  },
  {
    id: 'clinton',
    name: 'Bill Clinton',
    party: 'Democrat',
    platform: 'Tech Boom Expansion & Balanced Budget',
    taxRate: 16,
    heatPolicy: 'Fiscal Surplus',
    description: 'Drives rapid tech stock growth while maintaining a balanced budget.',
    executivePriority: 'tech_surplus',
  },
]

export const FED_CHAIRMEN_ROSTER = [
  {
    id: 'volcker',
    name: 'Paul Volcker',
    title: 'The Inflation Slayer',
    policyBias: 'Hawkish (Rate Hikes)',
    targetRate: 12.0,
    description: 'Executes aggressive interest rate hikes to slay inflation, cooling stock bubbles.',
  },
  {
    id: 'greenspan',
    name: 'Alan Greenspan',
    title: 'The Maestro',
    policyBias: 'Dovish Easy Money',
    targetRate: 3.5,
    description: 'Keeps interest rates low, inflating stock and real estate asset values.',
  },
  {
    id: 'bernanke',
    name: 'Ben Bernanke',
    title: 'Helicopter Ben',
    policyBias: 'Quantitative Easing',
    targetRate: 1.0,
    description: 'Pumps massive quantitative easing liquidity into crypto and stock markets.',
  },
  {
    id: 'yellen',
    name: 'Janet Yellen',
    title: 'Dovish Growth Architect',
    policyBias: 'Gradual Normalization',
    targetRate: 4.0,
    description: 'Maintains steady economic growth with predictable rate adjustments.',
  },
  {
    id: 'powell',
    name: 'Jerome Powers',
    title: 'High-Frequency Tightening',
    policyBias: 'Data-Dependent',
    targetRate: 5.5,
    description: 'Executes rapid rate hikes during inflation or rate cuts during market dips.',
  },
  {
    id: 'eccles',
    name: 'Marriner Eccles',
    title: 'Depression Stimulus Founder',
    policyBias: 'Fiscal Coordination',
    targetRate: 2.0,
    description: 'Coordinates central bank reserves with government infrastructure stimulus.',
  },
  {
    id: 'martin',
    name: 'William McChesney Martin',
    title: 'Punch Bowl Stripper',
    policyBias: 'Anti-Speculation',
    targetRate: 7.0,
    description: 'Raises margin requirements and interest rates whenever market speculation boils.',
  },
  {
    id: 'burns',
    name: 'Arthur Burns',
    title: 'Easy Credit Expander',
    policyBias: 'Monetary Expansion',
    targetRate: 3.0,
    description: 'Drives short-term market surges through loose credit expansion.',
  },
  {
    id: 'miller',
    name: 'G. William Miller',
    title: 'Short-Term Rate Watcher',
    policyBias: 'Neutral',
    targetRate: 5.0,
    description: 'Maintains moderate interest rates while watching short-term commodities.',
  },
  {
    id: 'meyer',
    name: 'Eugene Meyer',
    title: 'Early Liquidity Guardian',
    policyBias: 'Conservative Credit',
    targetRate: 4.5,
    description: 'Protects commercial bank solvency and gold reserve ratios.',
  },
]

export const FTC_CHAIRMEN_ROSTER = [
  {
    id: 'khan',
    name: 'Lena Cannon',
    title: 'Neo-Brandeisian Trust-Buster',
    bias: 'Aggressive Tech Monopoly Lawsuits',
    description: 'Launches antitrust lawsuits against dominant tech platforms and breaks monopolies.',
  },
  {
    id: 'ramirez',
    name: 'Edith Ramirez',
    title: 'Digital Privacy & Merger Reviewer',
    bias: 'Merger Enforcement',
    description: 'Blocks corporate mergers that threaten consumer data or fair market access.',
  },
  {
    id: 'simons_ftc',
    name: 'Joseph Simons',
    title: 'Platform Competition Chair',
    bias: 'Big Tech Investigations',
    description: 'Investigates insider trading and illegal corporate collusion.',
  },
  {
    id: 'muris',
    name: 'Timothy Muris',
    title: 'Empirical Fraud Enforcer',
    bias: 'Anti-Scam & Fraud Prosecution',
    description: 'Targets Underground call center scams and illicit criminal money laundering.',
  },
  {
    id: 'pertschuk',
    name: 'Michael Pertschuk',
    title: 'Consumer Protection Pioneer',
    bias: 'Unfair Trade Fines',
    description: 'Issues massive corporate fines on companies engaging in deceptive pricing.',
  },
  {
    id: 'kirkpatrick',
    name: 'Miles Kirkpatrick',
    title: 'Corporate Disclosure Chair',
    bias: 'Transparency Audit',
    description: 'Forces full disclosure of insider trading and illegal syndicate stock pools.',
  },
  {
    id: 'kovacic',
    name: 'William Kovacic',
    title: 'Global Antitrust Enforcer',
    bias: 'International Cartel Fines',
    description: 'Penalizes international cartels and global trade price-fixing.',
  },
  {
    id: 'majoras',
    name: 'Deborah Platt Majoras',
    title: 'Merger Retrospective Chair',
    bias: 'Merger Retrospective Review',
    description: 'Audits past corporate takeovers and demands asset divestitures.',
  },
  {
    id: 'leibowitz',
    name: 'Jon Leibowitz',
    title: 'Pharma & Pay-For-Delay Watcher',
    bias: 'Pay-For-Delay Enforcement',
    description: 'Fines corporate syndicates colluding to delay competitor market entry.',
  },
  {
    id: 'pitofsky',
    name: 'Robert Pitofsky',
    title: 'Vertical Monopoly Squeezer',
    bias: 'Vertical Integration Restrictions',
    description: 'Restricts vertical monopolies like Rockefeller Oil and Carnegie Steel.',
  },
]
