// The 50-item dataset (Traps, Spells/Relics, Equipment, Terrain, Legendary
// Artifacts). Each entry carries `target`/`mechanic`/`params` (and, for
// traps, `trigger`) so ddmItemResolver.js / DDMBoard.jsx can play a
// tractable subset for real. Anything without a recognized `mechanic` (or
// explicitly `mechanic: 'not_implemented'`) still shows in the Items panel
// with its real name/description, it just can't be used yet - same honest
// approach as the 150-monster catalog, for the same reason: 50 more unique
// effects (several needing graveyard tracking, multi-turn timers, or
// forced-movement chains that don't exist yet) can't all be hand-built and
// verified in one pass.

export const DDM_ITEM_CATALOG = [
  // --- Set 1: Traps & Hidden Hazards (placed face-down on an empty tile) ---
  { id: 'steel_jaw_snare', name: 'Steel-Jaw Snare', type: 'trap', cost: { defense: 1 }, target: 'any-empty', trigger: 'step',
    description: 'Triggers on step. Target takes 10 damage and loses all MOV for the turn.',
    mechanic: 'trap_damage', params: { amount: 10 } },
  { id: 'proximity_mine', name: 'Proximity Mine', type: 'trap', cost: { defense: 2 }, target: 'any-empty', trigger: 'step',
    description: 'Triggers on step. Deals 20 damage to the target and 10 to all adjacent tiles.',
    mechanic: 'trap_damage_splash', params: { amount: 20, splash: 10 } },
  { id: 'mirror_force_shield', name: 'Mirror Force Shield', type: 'trap', cost: { defense: 2 }, target: 'any-empty', trigger: 'attack',
    description: 'Triggers when adjacent ally is attacked. Reflects 100% of damage back to attacker.',
    mechanic: 'not_implemented' },
  { id: 'void_trapdoor', name: 'Void Trapdoor', type: 'trap', cost: { defense: 3 }, target: 'any-empty', trigger: 'step',
    description: 'Triggers on step. Instantly destroys any Level 1 or 2 monster.',
    mechanic: 'trap_instakill_low_level', params: { maxLevel: 2 } },
  { id: 'magnetic_pulse_mine', name: 'Magnetic Pulse-Mine', type: 'trap', cost: { defense: 1 }, target: 'any-empty', trigger: 'step',
    description: "Triggers on step. Target loses 2 ATK crests from their controller's pool.",
    mechanic: 'trap_crest_drain', params: { amount: 2, crestType: 'attack' } },
  { id: 'acid_sprinkler', name: 'Acid Sprinkler', type: 'trap', cost: { defense: 2 }, target: 'any-empty', trigger: 'step',
    description: 'Triggers on step. Target is Poisoned (takes 10 damage at the start of their next 2 turns).',
    mechanic: 'trap_poison', params: { amountPerTurn: 10, duration: 2 } },
  { id: 'time_stasis_ward', name: 'Time-Stasis Ward', type: 'trap', cost: { defense: 2 }, target: 'any-empty', trigger: 'step',
    description: 'Triggers on step. Target skips their next attack phase entirely.',
    mechanic: 'not_implemented' },
  { id: 'illusionary_decoy', name: 'Illusionary Decoy', type: 'trap', cost: { defense: 1 }, target: 'any-empty', trigger: 'attack',
    description: 'Triggers when attacked. The attack misses, and the attacker is pushed back 1 tile.',
    mechanic: 'not_implemented' },
  { id: 'sky_snare_net', name: 'S.K.Y. Snare-Net', type: 'trap', cost: { defense: 2 }, target: 'any-empty', trigger: 'step',
    description: 'Triggers on step. Disables all Magic effects of the target for 3 turns.',
    mechanic: 'trap_silence', params: { duration: 3 } },
  { id: 'overload_capacitor', name: 'Overload Capacitor', type: 'trap', cost: { defense: 3 }, target: 'any-empty', trigger: 'attack',
    description: 'Triggers when attacked. Deals 30 damage to the attacker and destroys 1 of their equipped items.',
    mechanic: 'not_implemented' },

  // --- Set 2: Spells & Relics (cast directly from the crest pool) ---
  { id: 'tome_of_the_triad', name: 'Tome of the Triad', type: 'spell', cost: { spell: 2 }, target: 'self',
    description: 'Draw 3 random crests and add them to your pool.',
    mechanic: 'gain_random_crests', params: { count: 3 } },
  { id: 'crimson_vitality_vial', name: 'Crimson Vitality Vial', type: 'spell', cost: { spell: 1 }, target: 'ally-any',
    description: 'Restore 20 HP to any allied monster.',
    mechanic: 'heal_target', params: { amount: 20 } },
  { id: 'orbital_teleport', name: 'Orbital Teleport', type: 'spell', cost: { spell: 2 }, target: 'not_implemented',
    description: 'Move one allied monster to any empty tile on the board.',
    mechanic: 'not_implemented' },
  { id: 'chain_lightning_scroll', name: 'Chain Lightning Scroll', type: 'spell', cost: { spell: 3 }, target: 'enemy-any',
    description: 'Deal 15 damage to a target, and 15 to the nearest enemy to that target.',
    mechanic: 'damage_target_and_nearest', params: { amount: 15 } },
  { id: 'meteor_strike', name: 'Meteor Strike', type: 'spell', cost: { spell: 4 }, target: 'any-empty',
    description: 'Deal 30 damage to a 2x2 grid anywhere on the board.',
    mechanic: 'damage_area_anchor', params: { amount: 30, radius: 1 } },
  { id: 'crest_syphon', name: 'Crest Syphon', type: 'spell', cost: { spell: 2 }, target: 'self',
    description: "Steal 2 random crests from the opponent's pool.",
    mechanic: 'steal_random_crests', params: { count: 2 } },
  { id: 'altar_of_resurrection', name: 'Altar of Resurrection', type: 'spell', cost: { spell: 4 }, target: 'not_implemented',
    description: 'Revive one destroyed Level 1 or 2 monster at full HP on your summon point.',
    mechanic: 'not_implemented' },
  { id: 'nullification_field', name: 'Nullification Field', type: 'spell', cost: { spell: 2 }, target: 'self',
    description: 'Remove all buffs, debuffs, and status effects from all monsters on the board.',
    mechanic: 'cleanse_board' },
  { id: 'berserkers_command', name: "Berserker's Command", type: 'spell', cost: { spell: 1 }, target: 'ally-any',
    description: 'Target ally gains +20 ATK but takes 10 damage at the end of the turn.',
    mechanic: 'berserk_buff', params: { amount: 20, selfDamage: 10 } },
  { id: 'kinetic_push', name: 'Kinetic Push', type: 'spell', cost: { spell: 1 }, target: 'any-monster',
    description: 'Push any monster (ally or enemy) 2 tiles in a straight line.',
    mechanic: 'not_implemented' },

  // --- Set 3: Equipment & Augments (attached to an ally, permanent) ---
  { id: 'pro_pneumatic_blast_gun', name: 'Pro-Pneumatic Blast-Gun', type: 'equip', cost: { attack: 2 }, target: 'ally-any',
    description: '+10 ATK. Grants a 3-tile range line-attack. (Machine/Cyberse only).',
    mechanic: 'equip_stat', params: { atk: 10 } },
  { id: 'inners_focus_band', name: "Inner's Focus Band", type: 'equip', cost: { spell: 1 }, target: 'ally-any',
    description: '+10 ATK. Equipped monster ignores movement penalties from hazards.',
    mechanic: 'equip_stat', params: { atk: 10 } },
  { id: 'heavy_tungsten_plates', name: 'Heavy Tungsten Plates', type: 'equip', cost: { defense: 2 }, target: 'ally-any',
    description: '+20 DEF. Equipped monster loses 1 MOV.',
    mechanic: 'equip_stat', params: { def: 20 } },
  { id: 'hover_thrusters', name: 'Hover Thrusters', type: 'equip', cost: { movement: 1 }, target: 'ally-any',
    description: '+2 MOV. Equipped monster can float over traps without triggering them.',
    mechanic: 'equip_trap_immune' },
  { id: 'thermal_plasma_blade', name: 'Thermal Plasma Blade', type: 'equip', cost: { attack: 2 }, target: 'ally-any',
    description: '+20 ATK. Damage dealt by this monster cannot be reduced by DEF.',
    mechanic: 'equip_stat_ignore_def', params: { atk: 20 } },
  { id: 'stealth_weave_cloak', name: 'Stealth-Weave Cloak', type: 'equip', cost: { spell: 2 }, target: 'ally-any',
    description: 'Equipped monster cannot be targeted by ranged attacks or spells.',
    mechanic: 'not_implemented' },
  { id: 'sniper_targeting_visor', name: 'Sniper Targeting Visor', type: 'equip', cost: { spell: 1 }, target: 'ally-any',
    description: '+10 ATK. Increases the range of any ranged attack by 2 tiles.',
    mechanic: 'equip_stat', params: { atk: 10 } },
  { id: 'vampiric_amulet', name: 'Vampiric Amulet', type: 'equip', cost: { spell: 3 }, target: 'ally-any',
    description: 'When the equipped monster deals damage, it heals HP equal to half the damage dealt.',
    mechanic: 'equip_lifesteal', params: { pct: 0.5 } },
  { id: 'deflector_shield_generator', name: 'Deflector Shield Generator', type: 'equip', cost: { defense: 2 }, target: 'ally-any',
    description: 'The first time this monster would take damage each turn, reduce that damage to 0.',
    mechanic: 'equip_shield_per_turn' },
  { id: 'spiked_carapace', name: 'Spiked Carapace', type: 'equip', cost: { attack: 1 }, target: 'ally-any',
    description: '+10 DEF. Attackers taking melee swings at this monster take 10 recoil damage.',
    mechanic: 'equip_stat_recoil', params: { def: 10, recoil: 10 } },

  // --- Set 4: Terrain & Grid Modifiers (placed on the board) ---
  { id: 'sky_aegis_hologrid', name: 'S.K.Y. Aegis Hologrid', type: 'terrain', cost: { spell: 2 }, target: 'any-empty',
    description: 'Transforms 3 adjacent empty tiles into a zone. Allies on these tiles gain +10 DEF.',
    mechanic: 'not_implemented' },
  { id: 'furnace_grate', name: 'Furnace Grate', type: 'terrain', cost: { spell: 2 }, target: 'any-empty',
    description: 'Transforms 1 tile into a hazard. Enemies ending their turn here take 15 damage.',
    mechanic: 'terrain_hazard_tile', params: { amount: 15 } },
  { id: 'high_voltage_fence', name: 'High-Voltage Fence', type: 'terrain', cost: { defense: 2 }, target: 'not_implemented',
    description: 'Creates an impassable 2-tile wide barrier. Lasts for 3 turns.',
    mechanic: 'not_implemented' },
  { id: 'rejuvenation_spring', name: 'Rejuvenation Spring', type: 'terrain', cost: { spell: 2 }, target: 'any-empty',
    description: 'Transforms 1 tile. Any monster (ally or enemy) ending their turn here heals 10 HP.',
    mechanic: 'terrain_heal_tile', params: { amount: 10 } },
  { id: 'cryo_ice_slick', name: 'Cryo-Ice Slick', type: 'terrain', cost: { movement: 1 }, target: 'not_implemented',
    description: 'Transforms 2 tiles in a line. Monsters moving across these tiles slide to the end instantly, costing 0 MOV.',
    mechanic: 'not_implemented' },
  { id: 'concrete_barricade', name: 'Concrete Barricade', type: 'terrain', cost: { defense: 1 }, target: 'any-empty',
    description: 'Places a 30 HP physical block on one tile. Must be destroyed to pass.',
    mechanic: 'terrain_barrier', params: { hp: 30, duration: 99 } },
  { id: 'factory_conveyor_belt', name: 'Factory Conveyor Belt', type: 'terrain', cost: { movement: 2 }, target: 'not_implemented',
    description: 'Transforms 3 tiles in a line. At the end of the turn, any unit on the belt is moved 1 space in the designated direction.',
    mechanic: 'not_implemented' },
  { id: 'toxic_smokescreen', name: 'Toxic Smokescreen', type: 'terrain', cost: { spell: 2 }, target: 'not_implemented',
    description: 'Transforms a 2x2 grid area. Ranged attacks cannot pass through this area.',
    mechanic: 'not_implemented' },
  { id: 'teleportation_pad', name: 'Teleportation Pad', type: 'terrain', cost: { spell: 3 }, target: 'not_implemented',
    description: 'Places Pad A and Pad B on two empty tiles. Stepping on one instantly teleports the unit to the other.',
    mechanic: 'not_implemented' },
  { id: 'quicksand_pit', name: 'Quicksand Pit', type: 'terrain', cost: { spell: 2 }, target: 'any-empty',
    description: 'Transforms 1 tile. Units entering this tile lose all remaining MOV crests for that turn.',
    mechanic: 'terrain_barrier', params: { hp: 1, duration: 99, quicksand: true } },

  // --- Set 5: Legendary Artifacts ---
  { id: 'the_golden_crest', name: 'The Golden Crest', type: 'artifact', cost: { spell: 5 }, target: 'self',
    description: 'Instantly fill your crest pool to maximum capacity (10 of each crest).',
    mechanic: 'fill_crest_pool' },
  { id: 'oblivion_engine', name: 'Oblivion Engine', type: 'artifact', cost: { spell: 4 }, target: 'self',
    description: 'Destroy all terrain modifiers, traps, and equipped items on the entire board.',
    mechanic: 'clear_board_effects' },
  { id: 'aegis_of_the_ancients', name: 'Aegis of the Ancients', type: 'artifact', cost: { defense: 4 }, target: 'self',
    description: 'Your Die Master becomes immune to direct damage for 2 full turns.',
    mechanic: 'dm_immune', params: { duration: 2 } },
  { id: 'doomsday_clock', name: 'Doomsday Clock', type: 'artifact', cost: { spell: 3 }, target: 'not_implemented',
    description: 'After 3 turns, all monsters on the board take 40 unavoidable damage.',
    mechanic: 'not_implemented' },
  { id: 'the_philosophers_stone', name: "The Philosopher's Stone", type: 'artifact', cost: { spell: 4 }, target: 'self',
    description: "Convert all ATK crests in your opponent's pool into DEF crests.",
    mechanic: 'convert_opponent_crests', params: { from: 'attack', to: 'defense' } },
  { id: 'emp_warhead', name: 'EMP Warhead', type: 'artifact', cost: { attack: 3 }, target: 'self',
    description: 'Silence all opponent monsters for 2 turns (approximates disabling Machine/Cyberse/Magic effects).',
    mechanic: 'silence_all_enemies', params: { duration: 2 } },
  { id: 'chrono_dial', name: 'Chrono-Dial', type: 'artifact', cost: { spell: 5 }, target: 'not_implemented',
    description: 'Take an immediate extra turn right after this one ends.',
    mechanic: 'not_implemented' },
  { id: 'soul_harvester_relic', name: 'Soul Harvester Relic', type: 'artifact', cost: { spell: 3 }, target: 'self',
    description: 'Whenever an enemy monster is destroyed in combat by your Attack, gain 1 MAG crest (rest of the match).',
    mechanic: 'soul_harvester_activate' },
  { id: 'orbital_laser_beacon', name: 'Orbital Laser Beacon', type: 'artifact', cost: { attack: 4 }, target: 'not_implemented',
    description: 'Target 1 tile. At the start of your next turn, anything on or adjacent to that tile is destroyed instantly.',
    mechanic: 'not_implemented' },
  { id: 'the_core_forge', name: 'The Core-Forge', type: 'artifact', cost: { spell: 4 }, target: 'ally-any',
    description: 'Upgrade one Level 2 or 3 allied monster into a random Level 4 monster from the catalog for free.',
    mechanic: 'upgrade_to_level4' },
]

export function getItemsByType(type) {
  return DDM_ITEM_CATALOG.filter((i) => i.type === type)
}

export function canAffordItem(bank, cost) {
  return Object.entries(cost).every(([type, amt]) => (bank[type] || 0) >= amt)
}

export function isItemImplemented(item) {
  return !!item.mechanic && item.mechanic !== 'not_implemented' && item.target !== 'not_implemented'
}
